### ISSUE TITLE
not working with custom diff tool

### ISSUE THREAD

**Issue by PierrickP** [relekang/lint-filter#127]
Hi, thanks for your tools.
it was introduced on [dotJs](https://www.dotjs.io/) by @zeke (thanks!)

But it's not working for me out of box.
I use a custom diff (https://github.com/so-fancy/diff-so-fancy)
my `cat ~/.gitconfig`

```
[pager]
   diff = diff-so-fancy | less --tabs=4 -RFX
```

After remove that line, still not working because of the colors (an other custom gitconfig ;) )
For that point, we could update [that line](https://github.com/relekang/lint-filter/blob/master/src/utils/git.js#L45) to include the [--no-color](https://git-scm.com/docs/git-diff#git-diff---no-color) option

For the custom diff, i don't know.
Do you have an idea to make it use the git original diff ?

**Comment by PierrickP** [comment]
My collegue send me (that)[https://github.com/so-fancy/diff-so-fancy#opting-out] with an RTFM :smile: 
I ll make a PR ...

**Comment by zeke** [comment]
Hi @PierrickP! How did my talk lead you to this module? Is it listed somewhere on http://electron.atom.io/userland/ ?

**Comment by relekang** [comment]
I think you saw this in my lightning talk about the technique that is the idea behind this library. Thanks for the pr 🙂

**Comment by PierrickP** [comment]
@zeke @relekang oups :p In any case, thanks both of you !
