### ISSUE TITLE
A webpack plugin?

### ISSUE THREAD

**Issue by OnkelTem** [relekang/lint-filter#135]
When I discovered this project one hour ago I was really excited about how I can use it.
I was sure it's gonna filter our files that haven't been changed, triggerring warnings only for the files that developer has actually changed. But it doesn't seem like this project has anything to do with what I personally reckon a main purpose. But maybe I'm wrong.

**Comment by relekang** [comment]
I don't get the title of the issue. This is not a webpack plugin it is a cli tool that you can use to filter eslint output.

> I was sure it's gonna filter our files that haven't been changed, triggerring warnings only for the files that developer has actually changed.

That is what it does.
